// Sans aucune dépendance : importé par le preload sandboxé (qui ne peut pas require() de modules tiers).
/** Noms de canaux IPC (main ↔ renderer). */
export const IPC = {
  appInfo: 'app:info',
  enginePing: 'engine:ping',
  keyStatus: 'key:status',
  keySave: 'key:save',
  keyTest: 'key:test',
  keyRemove: 'key:remove',
  modelsList: 'models:list',
  missionsList: 'missions:list',
  missionsGet: 'missions:get',
  missionsCreateDemo: 'missions:createDemo',
  missionsStart: 'missions:start',
  missionsPause: 'missions:pause',
  missionsResume: 'missions:resume',
  missionsCancel: 'missions:cancel',
  missionsRetry: 'missions:retry',
  missionsSimulate: 'missions:simulate',
  missionsEvents: 'missions:events',
  draftsList: 'drafts:list',
  draftsCreate: 'drafts:create',
  draftsGet: 'drafts:get',
  draftsSave: 'drafts:save',
  draftsRemove: 'drafts:remove',
  draftsFinalize: 'drafts:finalize',
  filesPick: 'files:pick',
  filesAdd: 'files:add',
  filesRemove: 'files:remove',
  filesList: 'files:list',
  catalogPresets: 'catalog:presets',
  catalogNorms: 'catalog:norms',
  sourcesList: 'sources:list',
  sourcesGet: 'sources:get',
  sourcesConfig: 'sources:config',
  sourcesSaveConfig: 'sources:saveConfig',
  sourcesSaveKey: 'sources:saveKey',
  sourcesRemoveKey: 'sources:removeKey',
  sourcesTest: 'sources:test',
  sourcesDemoResearch: 'sources:demoResearch',
  engineLive: 'engine:live',
  uiGet: 'ui:get',
  uiSet: 'ui:set',
} as const;
